language: java
sudo: false
jdk:
  - oraclejdk7
  
before_install:
  - cd atom-sdk/AtomSDK/
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn -Pcobertura clean cobertura:cobertura
after_success:
  - mvn coveralls:report